# Generated by Django 5.2.1 on 2025-06-07 15:17

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=64)),
                ('nazwisko', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('haslo', models.CharField(max_length=256)),
                ('telefon', models.CharField(blank=True, max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Lokacja',
            fields=[
                ('nazwa_lokacji', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('miasto', models.CharField(max_length=32)),
                ('adres', models.CharField(max_length=32)),
                ('kod_pocztowy', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=64)),
                ('nazwisko', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('haslo', models.CharField(max_length=256)),
                ('telefon', models.CharField(max_length=9)),
                ('zatwierdzony', models.BooleanField(default=False)),
                ('lokacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lokacja')),
            ],
        ),
        migrations.CreateModel(
            name='Zlecenie',
            fields=[
                ('id_zlecenia', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('status_zlecenia', models.IntegerField(choices=[(0, 'Oczekiwanie'), (1, 'W Realizacji'), (2, 'Zrealizowano'), (3, 'Zarchiwizowano')])),
                ('termin_zlecenia', models.DateTimeField(validators=[myapp.models.validate_time])),
                ('termin_realizacji', models.DateTimeField(blank=True)),
                ('model', models.CharField(blank=True, max_length=32)),
                ('nr_seryjny', models.CharField(max_length=32)),
                ('pakiet_diagnostyczny', models.BooleanField(default=False)),
                ('diagonza', models.TextField(default='nie wykupiono pakietu diagnostycznego')),
                ('id_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.klient')),
                ('id_lokacji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lokacja')),
                ('id_pracownika', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pracownik')),
            ],
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_zlecenia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usluga', to='myapp.zlecenie')),
            ],
        ),
    ]
