# Generated by Django 5.2.1 on 2025-06-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zlecenie',
            name='id_lokacji',
        ),
    ]
