# Generated by Django 5.2.1 on 2025-06-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_zlecenie_id_lokacji'),
    ]

    operations = [
        migrations.AddField(
            model_name='zlecenie',
            name='id_lokacji',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lokacja'),
        ),
    ]
