# Generated by Django 5.2.1 on 2025-06-07 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_zlecenie_id_lokacji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='id_lokacji',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.lokacja'),
        ),
    ]
