# Generated by Django 5.2.1 on 2025-06-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_zlecenie_id_lokacji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='status_zlecenia',
            field=models.IntegerField(choices=[(0, 'Oczekiwanie'), (1, 'W realizacji'), (2, 'Zrealizowano'), (3, 'Zarchiwizowano')]),
        ),
    ]
