# Generated by Django 5.2.1 on 2025-06-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_zlecenie_status_zlecenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='diagonza',
            field=models.TextField(default='. . .'),
        ),
    ]
