# Generated by Django 5.2.1 on 2025-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_zlecenie_diagonza'),
    ]

    operations = [
        migrations.AddField(
            model_name='zlecenie',
            name='pakiet_naprawy',
            field=models.BooleanField(default=False),
        ),
    ]
