# Generated by Django 5.2.1 on 2025-06-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_zlecenie_pakiet_naprawy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zlecenie',
            name='pakiet_naprawy',
        ),
    ]
