# Generated by Django 5.2.1 on 2025-06-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_zlecenie_pakiet_naprawy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usluga',
            old_name='id_zlecenia',
            new_name='order',
        ),
        migrations.AddField(
            model_name='usluga',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
