# Generated by Django 5.2.1 on 2025-06-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_id_zlecenia_usluga_order_usluga_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='telefon',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='diagonza',
            field=models.TextField(blank=True, default='. . .', null=True),
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='model',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='nr_seryjny',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='termin_realizacji',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
