# Generated by Django 5.2.1 on 2025-06-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_klient_telefon_alter_zlecenie_diagonza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usluga',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='service',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
