# Generated by Django 5.2.1 on 2025-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_usluga_price_alter_usluga_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usluga',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='service',
            field=models.CharField(max_length=256),
        ),
    ]
