# Generated by Django 5.2.1 on 2025-06-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_usluga_order_alter_usluga_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='dodatkowe_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
