# Generated by Django 5.2.1 on 2025-06-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_klient_dodatkowe_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='dodatkowe_info',
        ),
        migrations.AddField(
            model_name='zlecenie',
            name='dodatkowe_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
