# Generated by Django 5.2.1 on 2025-06-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_klient_dodatkowe_info_zlecenie_dodatkowe_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zlecenie',
            name='dodatkowe_info',
        ),
        migrations.AddField(
            model_name='klient',
            name='adres',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='firma',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='kod_pocztowy',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='nip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='zlecenie',
            name='notes',
            field=models.TextField(blank=True, default='. . .', null=True),
        ),
    ]
