# Generated by Django 5.2.1 on 2025-06-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_zlecenie_dodatkowe_info_klient_adres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='miasto',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='klient',
            name='adres',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='klient',
            name='firma',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='klient',
            name='kod_pocztowy',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nip',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
