# Generated by Django 5.2.1 on 2025-06-13 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_klient_miasto_alter_klient_adres_alter_klient_firma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrzadzenieTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='status_zlecenia',
            field=models.IntegerField(choices=[(0, 'Oczekiwanie'), (1, 'W realizacji'), (2, 'Zrealizowano'), (3, 'Zarchiwizowano')], default=0),
        ),
        migrations.CreateModel(
            name='UrzadzenieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64)),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelList', to='myapp.urzadzenietyp')),
            ],
        ),
        migrations.CreateModel(
            name='UrzadzenieUsluga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64)),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uslugaList', to='myapp.urzadzenietyp')),
            ],
        ),
    ]
