# Generated by Django 5.2.1 on 2025-06-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_urzadzenietyp_alter_zlecenie_status_zlecenia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urzadzenieusluga',
            name='typ',
        ),
        migrations.DeleteModel(
            name='UrzadzenieModel',
        ),
        migrations.DeleteModel(
            name='UrzadzenieTyp',
        ),
        migrations.DeleteModel(
            name='UrzadzenieUsluga',
        ),
    ]
